apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "teste"
  description: "Teste"
  annotations:
    github.com/project-slug: veecode-magalu/teste
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  lifecycle: experimental
  owner: "group:default/demo"
